name = 'biased'
license = 'MIT'
licenselink = 'https://github.com/imgios/not-much/blob/main/LICENSE'
description = 'A Hugo theme focused on simplicity and minimalism'

homepage = 'https://github.com/Hg03/biased'

demosite = 'https://giosuesulipano.it/not-much/'

tags = ['blog', 'website', 'simple', 'dark', 'minimal', 'responsive']

features = ['blog', 'reponsive', 'theme-palettes']

[author]
  name = 'Giosuè Sulipano'
  homepage = 'https://giosuesulipano.it'
