# The following line is needed
# when running the example site
# from a subdir of the theme
themesDir = "../../"

title = "biased"
theme = "biased"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "© {year} powered by hg03/biased"

[markup]
  [markup.highlight]
    style = 'catpuccin'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/Hg03/biased"
    weight = 4
